### ISSUE TITLE
Deployment should use configmap

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#86]
Could switch to using environment variables from a config map - this would make it far easier to change settings of a deployment. Probably not a good idea for secrets though!

```
      envFrom:
          - configMapRef:
              name: config-map-name
```

Or use the volume mounted approach:

```
    podspec
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config


    volumes:
        - name: config-volume
          configMap:
            name: config-map-name-here 
```

Env vars are easier to implement (because it is closer to what we currently do). But I think full file based config is better overall.

Also need to do somesort of reload on configmap changes. Perhaps can link via a hash of values?
